version: '2'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app/
      - pip-cache:/root/.cache
    environment:
      - DATABASE_URL=postgresql+pool://postgres@db:5432/postgres
    links:
      - "db:db"
    ports:
      - "8000:8000"
    stdin_open: true
    command: bash -c "pip install -r requirements_dev.txt &&
                      pip install -e ./ &&
                      gunicorn full_async_web_app_example.main:app --bind 0.0.0.0:8000 --worker-class aiohttp.worker.GunicornWebWorker -w 1 --reload"

  tests:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app/
      - pip-cache:/root/.cache
    environment:
      - DATABASE_URL=postgresql://postgres@db:5432/postgres
    links:
      - "db-test:db"

    command: bash -c "pip install -r requirements_dev.txt &&
                      pip install -e ./ &&
                      ptw ./ -- -s -rs --color=yes"
  db:
    image: postgres:9.6-alpine

  db-test:
    image: postgres:9.6-alpine

volumes:
  pip-cache:
    driver: local
